apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.156
  selector:
    app: grafana
  ports:
  - port: 3000
    name: http
    targetPort: 3000
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: service_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
 
