apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.153
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    name: http
    targetPort: 5000
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: service_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

