apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.152
  selector:
    app: wordpress
  ports:
  - port: 5050
    name: http
    targetPort: 5050
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: service_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
 
